# Generated by Django 4.2.6 on 2023-11-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=10)),
                ('planeta', models.CharField(max_length=50)),
                ('objeto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Winx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=10)),
                ('hada', models.CharField(max_length=50)),
                ('transformacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Witch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=10)),
                ('elemento', models.CharField(max_length=50)),
                ('signo', models.CharField(max_length=20)),
            ],
        ),
    ]
